/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package uiQuanLy;

import java.util.ArrayList;

import javax.swing.DefaultComboBoxModel;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

import dao.DAOSanPham;
import entity.LoaiSanPham;
import entity.Sach;
import entity.SanPham;
import entity.VanPhongPham;
import uiTimKiem.FormTimKiemSach;
import uiTimKiem.FormTimKiemVPP;

/**
 *
 * @author MSII
 */
public class GUIDanhSachVPP extends javax.swing.JPanel {

    /**
     * Creates new form QLNV
     */
    public GUIDanhSachVPP() {
        initComponents();
        loadData();
        loadTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblVPP = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        lblMaVPP = new javax.swing.JLabel();
        lblTenVPP = new javax.swing.JLabel();
        txtTenVPP = new javax.swing.JTextField();
        txtMaVPP = new javax.swing.JTextField();
        lblNSX = new javax.swing.JLabel();
        lblLoaiVPP = new javax.swing.JLabel();
        txtNSX = new javax.swing.JTextField();
        btnLamMoi = new javax.swing.JButton();
        btnTimKiem = new javax.swing.JButton();
        cboLoaiVPP = new javax.swing.JComboBox<>();

        setPreferredSize(new java.awt.Dimension(1536, 650));

        modeltblVPP = new  javax.swing.table.DefaultTableModel(
            new Object [][] {
                
            },
            new String [] {
                "STT", "Mã VPP", "Tên VPP", "NSX", "Loại VPP"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Integer.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        };
        jScrollPane1.setViewportView(tblVPP);
        tblVPP.setModel(modeltblVPP);

        jLabel1.setFont(new java.awt.Font("Arial", 1, 30)); // NOI18N
        jLabel1.setForeground(java.awt.Color.red);
        jLabel1.setText("DANH SÁCH VĂN PHÒNG PHẨM");

        lblMaVPP.setText("Mã VPP:");

        lblTenVPP.setText("Tên VPP:");

        lblNSX.setText("NSX:");

        lblLoaiVPP.setText("Loại VPP:");

        btnLamMoi.setText("Làm mới");
        btnLamMoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLamMoiActionPerformed(evt);
            }
        });

        btnTimKiem.setText("Tìm kiếm");
        btnTimKiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTimKiemActionPerformed(evt);
            }
        });

        modelcboLoai = new DefaultComboBoxModel<LoaiSanPham>();
        cboLoaiVPP.setModel(modelcboLoai);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(476, 476, 476))
            .addGroup(layout.createSequentialGroup()
                .addGap(83, 83, 83)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1364, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblTenVPP)
                            .addComponent(lblMaVPP))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtMaVPP, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtTenVPP, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(356, 356, 356)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblLoaiVPP)
                            .addComponent(lblNSX))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtNSX)
                            .addComponent(cboLoaiVPP, 0, 178, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnLamMoi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnTimKiem, javax.swing.GroupLayout.DEFAULT_SIZE, 171, Short.MAX_VALUE))))
                .addContainerGap(89, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblMaVPP)
                    .addComponent(txtMaVPP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblNSX)
                    .addComponent(txtNSX, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnLamMoi))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTenVPP)
                    .addComponent(txtTenVPP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblLoaiVPP)
                    .addComponent(btnTimKiem)
                    .addComponent(cboLoaiVPP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(78, 78, 78)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 314, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(99, 99, 99))
        );
        
    }// </editor-fold>    
    private void lamMoi() {
    	txtMaVPP.setText("");
		txtTenVPP.setText("");
		txtNSX.setText("");
		cboLoaiVPP.setSelectedIndex(0);
		loadTable();
		
    }
  
    private void loadTable(ArrayList<SanPham> dsVPP) {
    	modeltblVPP.setRowCount(0);
    	this.dsSanPham = dsVPP;
    		for (SanPham sanPham : dsSanPham) {
    			VanPhongPham vpp = (VanPhongPham)sanPham;
				Object row[] = {
						tblVPP.getRowCount()+1,
	    				vpp.getMaSP(),
	    				vpp.getTenSP(),
	    				vpp.getNhaSanXuat(),
	    				vpp.getLoaiSP()		
						};
						modeltblVPP.addRow(row);
			}
    }
    private void loadTable() {
    	modeltblVPP.setRowCount(0);  
//    	dsKH = daoKhachHang.getDanhsachKhachHang();
    	dsSanPham = daoSanPham.getDanhSachVPP();
    	for (SanPham sanPham : dsSanPham) {
    		VanPhongPham vpp = (VanPhongPham)sanPham;
    		Object row[]= {
    				tblVPP.getRowCount(),
    				vpp.getMaSP(),
    				vpp.getTenSP(),
    				vpp.getNhaSanXuat(),
    				vpp.getLoaiSP()	
    		};
    		modeltblVPP.addRow(row);
    	}
    }
    private void loadData() {
    	daoSanPham = new DAOSanPham();
    	dsLoaiSP = daoSanPham.getLoaiSanPhams(2);
    	modelcboLoai.addAll(dsLoaiSP);
    	dsSanPham = daoSanPham.getDanhSachVPP();
    	modelcboLoai.addAll(dsLoaiSP);

    }
    private void timKiem() {

		String maVPP ="";
		String tenVPP="";
		String TenTG="";
		String NSX ="";

		maVPP = txtMaVPP.getText();
		tenVPP =  txtTenVPP.getText();
		NSX = txtNSX.getText();
		
		String maLoai = "";
		if(cboLoaiVPP.getSelectedItem()!=null)
			maLoai =((LoaiSanPham)cboLoaiVPP.getSelectedItem()).getMaLoai();

		DAOSanPham daoSanPham = new DAOSanPham();
		ArrayList<SanPham> dsSanPham = daoSanPham.timKiemVPP(maVPP, tenVPP, NSX, maLoai);
//		System.out.println(dsSanPham.size());
//		this.dsSanPham= dsSanPham;
		loadTable(dsSanPham);
	}

    private void btnLamMoiActionPerformed(java.awt.event.ActionEvent evt) {                                             
        // TODO add your handling code here:
    	lamMoi();
    }
    private void btnTimKiemActionPerformed(java.awt.event.ActionEvent evt) {                                             
        // TODO add your handling code here:
    	timKiem();
    }

    
    // Variables declaration - do not modify                     
    private javax.swing.JButton btnLamMoi;
    private javax.swing.JButton btnTimKiem;
    private javax.swing.JComboBox<LoaiSanPham> cboLoaiVPP;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblLoaiVPP;
    private javax.swing.JLabel lblMaVPP;
    private javax.swing.JLabel lblNSX;
    private javax.swing.JLabel lblTenVPP;
    private javax.swing.JTable tblVPP;
    private javax.swing.JTextField txtMaVPP;
    private javax.swing.JTextField txtNSX;
    private javax.swing.JTextField txtTenVPP;
    private DefaultComboBoxModel<LoaiSanPham> modelcboLoai;
    
    private DefaultTableModel modeltblVPP;
    
    private ArrayList<LoaiSanPham> dsLoaiSP; 
    private DAOSanPham daoSanPham =  new DAOSanPham();
    private ArrayList<SanPham> dsSanPham; 
    // End of variables declaration                   
}
