/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package uiQuanLy;

import java.time.format.DateTimeFormatter;
import java.util.ArrayList;

import javax.swing.DefaultComboBoxModel;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;

import dao.DAOKhachHang;
import dao.DAOSanPham;
import entity.KhachHang;
import entity.LoaiSanPham;
import entity.NhanVien;
import entity.Sach;
import entity.SanPham;
import uiTimKiem.FormTimKiemSach;

/**
 *
 * @author MSII
 */
public class GUIDanhSachSach extends javax.swing.JPanel {

    /**
     * Creates new form QLKH
     */
    public GUIDanhSachSach() {
        initComponents();
        loadData();
        loadTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    
       // Variables declaration - do not modify                     
  
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        lblTTKH = new javax.swing.JLabel();
        lblMaSach = new javax.swing.JLabel();
        txtMaSach = new javax.swing.JTextField();
        lblTenTacGia = new javax.swing.JLabel();
        lblNamXB = new javax.swing.JLabel();
        txtNamXB = new javax.swing.JTextField();
        lblTenSach = new javax.swing.JLabel();
        txtTenSach = new javax.swing.JTextField();
        lblLoaiSach = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblSach = new javax.swing.JTable();
        txtTenTacGia = new javax.swing.JTextField();
        btnLamMoi = new javax.swing.JButton();
        cboLoaiSach = new javax.swing.JComboBox<>();
        btnTimKiem = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(1536, 650));

        lblTTKH.setFont(new java.awt.Font("Arial", 1, 30)); // NOI18N
        lblTTKH.setForeground(java.awt.Color.red);
        lblTTKH.setText("DANH SÁCH SÁCH");

        lblMaSach.setLabelFor(txtMaSach);
        lblMaSach.setText("Mã sách:");
        lblMaSach.setToolTipText("");

        lblTenTacGia.setText("Tên tác giả:");

        lblNamXB.setLabelFor(txtNamXB);
        lblNamXB.setText("Năm XB:");
        lblNamXB.addHierarchyBoundsListener(new java.awt.event.HierarchyBoundsListener() {
            public void ancestorMoved(java.awt.event.HierarchyEvent evt) {
                lblNamXBAncestorMoved(evt);
            }
            public void ancestorResized(java.awt.event.HierarchyEvent evt) {
            }
        });

        txtNamXB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNamXBActionPerformed(evt);
            }
        });

        lblTenSach.setLabelFor(txtTenSach);
        lblTenSach.setText("Tên sách:");

        lblLoaiSach.setText("Loại sách:");

        modeltblSach = new  javax.swing.table.DefaultTableModel(
            new Object [][] {
               
            },
            new String [] {
                "STT", "Mã sách", "Tên sách", "Loại sách", "Tên tác giả", "Năm XB"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        };
        
        jScrollPane1.setViewportView(tblSach);
        tblSach.setModel(modeltblSach);
        

        txtTenTacGia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTenTacGiaActionPerformed(evt);
            }
        });

        btnLamMoi.setText("Làm mới");
        btnLamMoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLamMoiActionPerformed(evt);
            }
        });

        modelcboLoai = new DefaultComboBoxModel<LoaiSanPham>();
        cboLoaiSach.setModel(modelcboLoai);

        btnTimKiem.setText("Tìm kiếm");
        btnTimKiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTimKiemActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblTenTacGia)
                            .addComponent(lblLoaiSach))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtTenTacGia, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cboLoaiSach, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(584, 584, 584))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(lblTTKH)
                        .addGap(600, 600, 600))))
            .addGroup(layout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblTenSach)
                            .addComponent(lblMaSach))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(17, 17, 17)
                                .addComponent(txtTenSach, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(txtMaSach)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 893, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblNamXB)
                                .addGap(18, 18, 18)
                                .addComponent(txtNamXB, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(btnLamMoi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1410, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(60, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(641, 641, 641))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTTKH, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(lblMaSach)
                                .addComponent(txtMaSach, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lblLoaiSach)
                                .addComponent(cboLoaiSach, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(18, 18, 18)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(lblTenSach)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lblTenTacGia)
                                    .addComponent(txtTenTacGia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGap(3, 3, 3))
                        .addComponent(txtTenSach, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblNamXB)
                            .addComponent(txtNamXB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(btnLamMoi)))
                .addGap(50, 50, 50)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 311, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(btnTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(50, Short.MAX_VALUE))
        );
        
    }// </editor-fold>
    public void loadTbltoForm(int row) {
    	
 	}
    private void lamMoi() {
    	txtMaSach.setText("");
		txtTenSach.setText("");
		txtNamXB.setText("");
		
		cboLoaiSach.setSelectedIndex(0);
		txtTenTacGia.setText("");
		
		loadTable();
		
    }
    
    private void loadTable(ArrayList<SanPham> dsSP) {
    	modeltblSach.setRowCount(0);
    	this.dsSanPham = dsSP;
    		for (SanPham sanPham : dsSanPham) {
    			Sach sach = (Sach)sanPham;
				Object row[] = {
						tblSach.getRowCount()+1,
	    				sach.getMaSP(),
	    				sach.getTenSP(),
	    				sach.getLoaiSP(),
	    				sach.getTacGia().getTenTG(),
	    				sach.getNamXuatBan(),		
						};
						modeltblSach.addRow(row);
			}
    }
    
    private void loadTable() {
    	modeltblSach.setRowCount(0); 
    	dsSanPham = daoSanPham.getDanhSachSach();
    	for (SanPham sanPham : dsSanPham) {
    		Sach sach = (Sach)sanPham;
    		Object row[]= {
    				tblSach.getRowCount(),
    				sach.getMaSP(),
    				sach.getTenSP(),
    				sach.getLoaiSP(),
    				sach.getTacGia().getTenTG(),
    				sach.getNamXuatBan(),
    				
    		};
    		modeltblSach.addRow(row);
    	}
    }
    private void loadData() {
    	daoSanPham = new DAOSanPham();
    	dsLoaiSP = daoSanPham.getLoaiSanPhams(1);
    	modelcboLoai.addAll(dsLoaiSP);
    	dsSanPham = daoSanPham.getDanhSachSach();
    	modelcboLoai.addAll(dsLoaiSP);
    	
    }
    private void timKiem() {

			String maSach ="";
			String TenSach="";
			String TenTG="";
			String namXB ="";

			maSach = txtMaSach.getText();
			TenSach =  txtTenSach.getText();
			TenTG = txtTenTacGia.getText();
			namXB = txtNamXB.getText();
			
			String maLoai = "";
			if(cboLoaiSach.getSelectedItem()!=null)
				maLoai =((LoaiSanPham)cboLoaiSach.getSelectedItem()).getMaLoai();

			DAOSanPham daoSanPham = new DAOSanPham();
			ArrayList<SanPham> dsSanPham = daoSanPham.timKiemSach(maSach, TenSach, TenTG, namXB, maLoai);
			System.out.println(dsSanPham.size());
//			this.dsSanPham= dsSanPham;
			loadTable(dsSanPham);
		}
	

    private void txtNamXBActionPerformed(java.awt.event.ActionEvent evt) {                                         
        // TODO add your handling code here:
    }                                        

    private void lblNamXBAncestorMoved(java.awt.event.HierarchyEvent evt) {                                       
        // TODO add your handling code here:
    }                                      

    private void txtTenTacGiaActionPerformed(java.awt.event.ActionEvent evt) {                                             
        // TODO add your handling code here:
    } 
    private void btnLamMoiActionPerformed(java.awt.event.ActionEvent evt) {                                             
        // TODO add your handling code here:
    	lamMoi();
    }
    private void btnTimKiemActionPerformed(java.awt.event.ActionEvent evt) {                                             
        // TODO add your handling code here:
    	timKiem();
    }
    


    // Variables declaration - do not modify                     
    private javax.swing.JButton btnLamMoi;
    private javax.swing.JButton btnTimKiem;
    private javax.swing.JComboBox<LoaiSanPham> cboLoaiSach;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblLoaiSach;
    private javax.swing.JLabel lblMaSach;
    private javax.swing.JLabel lblNamXB;
    private javax.swing.JLabel lblTTKH;
    private javax.swing.JLabel lblTenSach;
    private javax.swing.JLabel lblTenTacGia;
    private javax.swing.JTable tblSach;
    private javax.swing.JTextField txtMaSach;
    private javax.swing.JTextField txtNamXB;
    private javax.swing.JTextField txtTenSach;
    private javax.swing.JTextField txtTenTacGia;
    private DefaultComboBoxModel<LoaiSanPham> modelcboLoai;
    private javax.swing.JComboBox<LoaiSanPham> cboLoai;

    private DefaultTableModel modeltblSach;
    
    private ArrayList<LoaiSanPham> dsLoaiSP;
  
    private DAOSanPham daoSanPham = new DAOSanPham();
    private ArrayList<SanPham> dsSanPham; 
    // End of variables declaration                   
}
