/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package uiQuanLy;

import java.awt.event.MouseEvent;
import java.awt.event.MouseListener;
import java.sql.SQLException;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.util.ArrayList;

import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;
import javax.swing.text.JTextComponent;

import entity.ChucVu;
import entity.KhachHang;
import dao.DAOKhachHang;
import dao.DAONhanVien;
import entity.NhanVien;
import uiMenu.GUIMenuQuanLy;
import uiTimKiem.FormTimKiemKhachHang;
import uiTimKiem.FormTimKiemNhanVien;

/**
 *
 * @author MSII
 */
public class GUIQuanLyNhanVien extends javax.swing.JPanel {

    /**
     * Creates new form QLNV
     */
    public GUIQuanLyNhanVien() {
        initComponents();
        loadTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        lblGioiTinh = new javax.swing.JLabel();
        lblCCCD = new javax.swing.JLabel();
        txtCCCD = new javax.swing.JTextField();
        lblMaNV = new javax.swing.JLabel();
        txtMaNV = new javax.swing.JTextField();
        lblNgaySinh = new javax.swing.JLabel();
        jdcNgaySinh = new com.toedter.calendar.JDateChooser();
        lblTenNV = new javax.swing.JLabel();
        txtTenNV = new javax.swing.JTextField();
        lblChucVu = new javax.swing.JLabel();
        lblNgayVaoLam = new javax.swing.JLabel();
        lblSDT = new javax.swing.JLabel();
        txtSDT = new javax.swing.JTextField();
        lblDiaChi = new javax.swing.JLabel();
        txtDiaChi = new javax.swing.JTextField();
        btnThem = new javax.swing.JButton();
        btnXoa = new javax.swing.JButton();
        btnSua = new javax.swing.JButton();
        btnLamMoi = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblNhanVien = new javax.swing.JTable();
        btnTimKiem = new javax.swing.JButton();
        cboGioiTinh = new javax.swing.JComboBox<>();
        cboChucVu = new javax.swing.JComboBox<>();
        jdcNgayVaoLam = new com.toedter.calendar.JDateChooser();
        jLabel1 = new javax.swing.JLabel();
        
        txtMaNV.setEditable(false);

        setPreferredSize(new java.awt.Dimension(1536, 650));

        lblGioiTinh.setText("Giới tính:");

        lblCCCD.setText("CMND/CCCD:");

        txtCCCD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCCCDActionPerformed(evt);
            }
        });

        lblMaNV.setText("Mã nhân viên:");
        lblMaNV.setToolTipText("");

        txtMaNV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMaNVActionPerformed(evt);
            }
        });

        lblNgaySinh.setText("Ngày sinh:");

        lblTenNV.setText("Tên nhân viên:");

        txtTenNV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTenNVActionPerformed(evt);
            }
        });

        lblChucVu.setText("Chức vụ:");

        lblNgayVaoLam.setText("Ngày vào làm:");

        lblSDT.setText("Số điện thoại:");

        txtSDT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSDTActionPerformed(evt);
            }
        });

        lblDiaChi.setText("Địa chỉ:");

        txtDiaChi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDiaChiActionPerformed(evt);
            }
        });

        btnThem.setText("Thêm");
        btnThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
            	btnThemActionPerformed(evt);
            }
        });

        btnXoa.setText("Xóa");
        btnXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaActionPerformed(evt);
            }
        });

        btnSua.setText("Sửa");
        btnSua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuaActionPerformed(evt);
            }
        });

        btnLamMoi.setText("Làm mới");
        btnLamMoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
            	btnLamMoiActionPerformed(evt);
            }
        });
        btnLamMoi.setMaximumSize(new java.awt.Dimension(72, 23));
        btnLamMoi.setMinimumSize(new java.awt.Dimension(72, 23));

        modeltblNV = new javax.swing.table.DefaultTableModel(
            new Object [][] {
                
            },
            new String [] {
                "STT", "Mã nhân viên", "Tên nhân viên", "CMND", "SDT", "Ngày sinh", "Giới tính", "Địa chỉ", "Ngày vào làm", "Tên chức vụ"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Integer.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        };
        tblNhanVien.setModel(modeltblNV);
        
        tblNhanVien.addMouseListener(new MouseListener() {
			
			@Override
			public void mouseReleased(MouseEvent e) {
				// TODO Auto-generated method stub
				
			}
			
			@Override
			public void mousePressed(MouseEvent e) {
				// TODO Auto-generated method stub
				
			}
			
			@Override
			public void mouseExited(MouseEvent e) {
				// TODO Auto-generated method stub
				
			}
			
			@Override
			public void mouseEntered(MouseEvent e) {
				// TODO Auto-generated method stub
				
			}
			
			@Override
			public void mouseClicked(MouseEvent e) {
				// TODO Auto-generated method stub
				int row = tblNhanVien.getSelectedRow();
				loadTbltoForm(row);
			}
		});
        
        jScrollPane1.setViewportView(tblNhanVien);

        btnTimKiem.setText("Tìm kiếm");
        btnTimKiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTimKiemActionPerformed(evt);
            }
        });

        cboGioiTinh.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Nam", "Nữ" }));
        cboGioiTinh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboGioiTinhActionPerformed(evt);
            }
        });

        modelCboChucVu = new DefaultComboBoxModel<ChucVu>();
        cboChucVu.setModel(modelCboChucVu);
        loadChucVu();

        jLabel1.setFont(new java.awt.Font("Arial", 1, 30)); // NOI18N
        jLabel1.setForeground(java.awt.Color.red);
        jLabel1.setText("QUẢN LÝ NHÂN VIÊN");
        jdcNgaySinh.setDateFormatString("yyyy-MM-dd");
        jdcNgayVaoLam.setDateFormatString("yyyy-MM-dd");
        ((JTextComponent)jdcNgaySinh.getDateEditor().getUiComponent()).setEditable(false);;
        ((JTextComponent)jdcNgayVaoLam.getDateEditor().getUiComponent()).setEditable(false);;
        
        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(548, 548, 548)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lblNgayVaoLam)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jdcNgayVaoLam, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lblMaNV)
                                            .addComponent(lblNgaySinh))
                                        .addGap(15, 15, 15)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(txtMaNV)
                                            .addComponent(jdcNgaySinh, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 188, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblTenNV)
                                    .addComponent(lblSDT)
                                    .addComponent(lblChucVu))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtTenNV, javax.swing.GroupLayout.DEFAULT_SIZE, 295, Short.MAX_VALUE)
                                    .addComponent(txtSDT, javax.swing.GroupLayout.DEFAULT_SIZE, 295, Short.MAX_VALUE)
                                    .addComponent(cboChucVu, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(203, 203, 203)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblCCCD)
                                    .addComponent(lblGioiTinh)
                                    .addComponent(lblDiaChi))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtDiaChi, javax.swing.GroupLayout.PREFERRED_SIZE, 295, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(txtCCCD, javax.swing.GroupLayout.DEFAULT_SIZE, 295, Short.MAX_VALUE)
                                        .addComponent(cboGioiTinh, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 15, Short.MAX_VALUE)))
                        .addGap(36, 36, 36))))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(338, 338, 338)
                        .addComponent(btnThem, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(43, 43, 43)
                        .addComponent(btnXoa, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(48, 48, 48)
                        .addComponent(btnSua, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(49, 49, 49)
                        .addComponent(btnLamMoi, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(646, 646, 646)
                        .addComponent(btnTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 414, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(40, 40, 40)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lblMaNV)
                                    .addComponent(txtMaNV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lblNgaySinh)
                                    .addComponent(jdcNgaySinh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblNgayVaoLam)
                                    .addComponent(jdcNgayVaoLam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lblTenNV)
                                    .addComponent(txtTenNV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lblSDT)
                                    .addComponent(txtSDT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(15, 15, 15)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lblChucVu)
                                    .addComponent(cboChucVu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnXoa, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(btnLamMoi, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(btnSua, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(btnThem, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(87, 87, 87)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblGioiTinh)
                            .addComponent(cboGioiTinh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtCCCD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblCCCD))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblDiaChi)
                            .addComponent(txtDiaChi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 314, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        setEditableForm(false);
    }// </editor-fold> 
    
    private void lamMoi() {
    	txtMaNV.setText("");
		txtTenNV.setText("");
		txtCCCD.setText("");
		txtSDT.setText("");
		((JTextField)jdcNgaySinh.getDateEditor().getUiComponent()).setText("");
		cboGioiTinh.setSelectedIndex(0);
		txtDiaChi.setText("");
		((JTextField)jdcNgayVaoLam.getDateEditor().getUiComponent()).setText("");
		cboChucVu.setSelectedIndex(0);
		
		loadTable();
		btnThem.setText("Thêm");
    	btnXoa.setEnabled(true);
		btnSua.setEnabled(true);
    }
    
    private void loadChucVu() {
    	ArrayList<ChucVu> dsCV = daoNhanVien.getDanhsachChucVu();
    	modelCboChucVu.addAll(dsCV);
    }
    
    private void loadTable(ArrayList<NhanVien> dsNV) {
    	modeltblNV.setRowCount(0);
    	this.dsNV = dsNV;
    		for (NhanVien nhanVien : dsNV) {
				Object row[] = {
						tblNhanVien.getRowCount(),
						nhanVien.getMaNV(), 
						nhanVien.getTenNV(), 
						nhanVien.getcMND(), 
						nhanVien.getsDT(),
						nhanVien.getNgaySinh(),
						nhanVien.isGioiTinh()==true? "Nam":"Nữ",
						nhanVien.getDiaChi(),
						nhanVien.getNgayVaoLam(),
						nhanVien.getChucVu().getTenChucVu(),
						};
				
						
						modeltblNV.addRow(row);
			}
    }
    
    private void loadTable() {
    	modeltblNV.setRowCount(0);
    	dsNV = daoNhanVien.getDanhsachNhanVien();
    		for (NhanVien nhanVien : dsNV) {
				Object row[] = {
						tblNhanVien.getRowCount(),
						nhanVien.getMaNV(), 
						nhanVien.getTenNV(), 
						nhanVien.getcMND(), 
						nhanVien.getsDT(),
						nhanVien.getNgaySinh(),
						nhanVien.isGioiTinh()==true? "Nam":"Nữ",
						nhanVien.getDiaChi(),
						nhanVien.getNgayVaoLam(),
						nhanVien.getChucVu().getTenChucVu(),
						};
				
						
						modeltblNV.addRow(row);
			}
			
		}

    public void loadTbltoForm(int row) {
    	NhanVien nhanVien = dsNV.get(row);
 		txtMaNV.setText(nhanVien.getMaNV());
 		txtTenNV.setText(nhanVien.getTenNV());
 		txtCCCD.setText(nhanVien.getcMND());
 		txtSDT.setText(nhanVien.getsDT());
 		((JTextField)jdcNgaySinh.getDateEditor().getUiComponent())
 		.setText(nhanVien.getNgaySinh().format(DateTimeFormatter.ofPattern("yyyy-MM-dd")));
 		cboGioiTinh.setSelectedItem(nhanVien.isGioiTinh()?"Nam":"Nữ");
 		txtDiaChi.setText(nhanVien.getDiaChi());
 		((JTextField)jdcNgayVaoLam.getDateEditor().getUiComponent())
 		.setText(nhanVien.getNgayVaoLam().format(DateTimeFormatter.ofPattern("yyyy-MM-dd")));
 		cboChucVu.setSelectedItem(nhanVien.getChucVu());
 	}
    public void setEditableForm(boolean st) {
    	
		txtTenNV.setEditable(st);
		txtCCCD.setEditable(st);
		cboGioiTinh.setEnabled(st);
		txtSDT.setEditable(st);
		jdcNgaySinh.setEnabled(st);
		jdcNgayVaoLam.setEnabled(st);
		txtDiaChi.setEditable(st);
		cboChucVu.setEnabled(st);
		
	}
    
    private void timKiemNV() {
    	FormTimKiemNhanVien formTimKiemNhanVien = new FormTimKiemNhanVien();
    	int result = JOptionPane.showConfirmDialog(null, formTimKiemNhanVien, "Tìm kiếm nhân viên",
				JOptionPane.OK_CANCEL_OPTION, 
				JOptionPane.PLAIN_MESSAGE);
		if (result == JOptionPane.OK_OPTION) {
			String tenNV = "";
			String cMND = "";
			String ngaySinh = "";
			tenNV = formTimKiemNhanVien.getTxtTenNV().getText();
			cMND = formTimKiemNhanVien.getTxtCCCD().getText();
			ngaySinh = ((JTextField)jdcNgaySinh.getDateEditor().getUiComponent()).getText();
			boolean gioiTinh = formTimKiemNhanVien.getJrdNam().isSelected();
			
			DAONhanVien daoNhanVien = new DAONhanVien();
			ArrayList<NhanVien> dsNV =  daoNhanVien.timKiemNhanVien(tenNV, cMND, ngaySinh, gioiTinh);
//			GUIMenuQuanLy.showPanel(new GUIQuanLyNhanVien());
//			System.out.println(dsNV.size());
	
			loadTable(dsNV);
		}			
    }
    
    private void themNV(){
    	
    	String maNV = daoNhanVien.getMaNV();
    	if(btnThem.getText().equals("Thêm")) {
    		lamMoi();
    		btnThem.setText("Xác nhận");
	    	
	    	txtMaNV.setText(maNV);
    		setEditableForm(true);
    		btnXoa.setEnabled(false);
    		btnSua.setEnabled(false);
    	} else {
    		if(validData()) {
    		
	    	String tenNV = txtTenNV.getText();
	    	String cMND = txtCCCD.getText();
	    	String sDT = txtSDT.getText();
	    	String ngaySinh = ((JTextField)jdcNgaySinh.getDateEditor().getUiComponent()).getText();
	    	String gioiTinh = cboGioiTinh.getSelectedItem().toString();
	    	String diaChi = txtDiaChi.getText();
	    	String ngayVaoLam = ((JTextField)jdcNgayVaoLam.getDateEditor().getUiComponent()).getText();
	    	ChucVu chucVu = (ChucVu)cboChucVu.getSelectedItem();
	    	
	    	NhanVien nhanVien = new NhanVien(maNV, tenNV, cMND,
	    			LocalDate.parse(ngaySinh, DateTimeFormatter.ofPattern("yyyy-MM-dd")), 
	    			gioiTinh.equals("Nam")?true:false, 
	    			sDT,
	    			diaChi, 
	    			LocalDate.parse(ngayVaoLam, DateTimeFormatter.ofPattern("yyyy-MM-dd")), 
	    			chucVu );
	    	try {
	    		daoNhanVien.them_NV(nhanVien);
	    		modeltblNV.addRow(new Object[] {tblNhanVien.getRowCount(),  nhanVien.getMaNV(), 
	    				nhanVien.getTenNV(), 
	    				nhanVien.getcMND(),
	    				nhanVien.getsDT(),
	    				nhanVien.getNgaySinh(),
	    				nhanVien.isGioiTinh(),
	    				nhanVien.getDiaChi(),	
	    				nhanVien.getNgayVaoLam(),
	    				nhanVien.getChucVu(),
	    		});
	    	} catch (Exception e) {
	    		e.printStackTrace();
	    	}
	    	btnThem.setText("Thêm");
	    	btnXoa.setEnabled(true);
    		btnSua.setEnabled(true);
	    	loadTable();
    		}
	    }	
    }
    public void xoaNV() {
    	int row = tblNhanVien.getSelectedRow();
    	if (row ==-1) {
    		JOptionPane.showMessageDialog(this, "Vui lòng chọn dòng cần xóa");
    		return;
    	}
    	if (JOptionPane.showConfirmDialog(null,"Xác nhận xóa")==JOptionPane.YES_OPTION){
    		try {
				daoNhanVien.xoa_NV(tblNhanVien.getValueAt(row, 1).toString());
				JOptionPane.showMessageDialog(this, "Xóa thành công");
			} catch (Exception e) {
				// TODO: handle exception
				e.printStackTrace();
			}
    		loadTable();
    	
    	}
    
    	
    }
    public void capNhatNV() {
	   String maNV = txtMaNV.getText();
	   if(btnSua.getText().equals("Sửa")) {
		btnSua.setText("Xác nhận"); 
		btnLamMoi.setText("Hủy");
	    	
		setEditableForm(true);
		btnThem.setEnabled(false);
		btnXoa.setEnabled(false);
	} else {
		
	
	   
	   	if(validData()) {
	   		String tenNV = txtTenNV.getText();
	    	String cMND = txtCCCD.getText();
	    	String sDT = txtSDT.getText();
	    	String ngaySinh = ((JTextField)jdcNgaySinh.getDateEditor().getUiComponent()).getText();
	    	String gioiTinh = cboGioiTinh.getSelectedItem().toString();
	    	String diaChi = txtDiaChi.getText();
	    	String ngayVaoLam = ((JTextField)jdcNgayVaoLam.getDateEditor().getUiComponent()).getText();
	    	ChucVu chucVu = (ChucVu)cboChucVu.getSelectedItem();
	    	
	    	NhanVien nhanVien = new NhanVien(maNV, tenNV, cMND,
	    			LocalDate.parse(ngaySinh, DateTimeFormatter.ofPattern("yyyy-MM-dd")), 
	    			gioiTinh.equals("Nam")?true:false, 
	    			sDT,
	    			diaChi, 
	    			LocalDate.parse(ngayVaoLam, DateTimeFormatter.ofPattern("yyyy-MM-dd")), 
	    			chucVu );
	   	try {
	   		daoNhanVien.capNhat(nhanVien);
 		loadTable();
	
	   	} catch (Exception e) {
			// TODO: handle exception
		}
	   	btnSua.setText("Sửa");
		btnLamMoi.setText("Làm mới");
 	btnThem.setEnabled(true);
		btnXoa.setEnabled(true);
		lamMoi(); 
	   	}
	}
		
}
    private boolean validData() {
 	   
 	   String tenNV = txtTenNV.getText().trim();
 	   String sDT = txtSDT.getText().trim();
 	   String diaChi = txtDiaChi.getText().trim();
 	   String cCCD = txtCCCD.getText().trim();
 	   String ngaySinh = ((JTextField)jdcNgaySinh.getDateEditor().getUiComponent()).getText();
 	   String ngayVaoLam = ((JTextField)jdcNgayVaoLam.getDateEditor().getUiComponent()).getText();
 	   
 	   if(!(tenNV.length() > 0 && tenNV.matches("^[A-Z][a-z]+(\\s[A-Z][a-z]+)+"))) {
 		   JOptionPane.showMessageDialog(this, "Error: Tên nhân viên phải viết hoa chữ cái đầu mỗi từ và có ít nhất 2 từ !");
 		   txtTenNV.requestFocus();
 		   return false;
 	   }
 	   if(LocalDate.parse(ngaySinh, DateTimeFormatter.ofPattern("yyyy-MM-dd")).isAfter(LocalDate.now())) {
		   JOptionPane.showMessageDialog(this, "Error:Ngày sinh không được sau ngày hiện tại !");
		  
		   return false;
	   }
 	   if(!(sDT.length() > 0 && sDT.matches("[0]\\d{9}"))) {
 		   JOptionPane.showMessageDialog(this, "Error: SDT bắt đầu bằng 0 và có 10 chữ số");
 		   txtSDT.requestFocus();
 		   return false;
 	   }
 	   if(!(cCCD.length() > 0 && cCCD.matches("[0-9]{9}|[0-9]{12}") )) {
		   JOptionPane.showMessageDialog(this, "Error: Căn cước công dân phải có đủ 9 hoặc 12 số  !");
		   txtCCCD.requestFocus();
		   return false;
	   }
 	   if(LocalDate.parse(ngayVaoLam, DateTimeFormatter.ofPattern("yyyy-MM-dd")).isAfter(LocalDate.now())) {
		   JOptionPane.showMessageDialog(this, "Error:Ngày vào làm không được sau ngày hiện tại !");
		   return false;
	   }
 	   if(cboChucVu.getSelectedItem() == null) {
 		   JOptionPane.showMessageDialog(this, "Error:Chọn chức vụ !");
		  
		   return false;
 		   
 	   }
 	   if(!(diaChi.length() > 0 )) {
 		   JOptionPane.showMessageDialog(this, "Error: Địa chỉ không được để trống !");
 		   txtDiaChi.requestFocus();
 		   return false;
 	   }
 	   return true;   
   }
    
    private void txtCCCDActionPerformed(java.awt.event.ActionEvent evt) {                                        
        // TODO add your handling code here:
    	
    }                                       

    private void txtTenNVActionPerformed(java.awt.event.ActionEvent evt) {                                         
        // TODO add your handling code here:
    }                                        

    private void txtMaNVActionPerformed(java.awt.event.ActionEvent evt) {                                        
        // TODO add your handling code here:
    }                                       

    private void txtSDTActionPerformed(java.awt.event.ActionEvent evt) {                                       
        // TODO add your handling code here:
    }                                      

    private void txtDiaChiActionPerformed(java.awt.event.ActionEvent evt) {                                          
        // TODO add your handling code here:
    }                                         

    private void btnSuaActionPerformed(java.awt.event.ActionEvent evt) {                                       
        // TODO add your handling code here:
    	capNhatNV();
    }                                      

    private void btnTimKiemActionPerformed(java.awt.event.ActionEvent evt) {                                           
        // TODO add your handling code here:
    	timKiemNV();
    } 
    private void btnThemActionPerformed(java.awt.event.ActionEvent evt) {                                           
        // TODO add your handling code here:
    	themNV();
    }
    private void btnLamMoiActionPerformed(java.awt.event.ActionEvent evt) {                                           
        // TODO add your handling code here:
    	lamMoi();
    }
    private void btnXoaActionPerformed(java.awt.event.ActionEvent evt) {                                           
        // TODO add your handling code here:
    	xoaNV();
    }

    private void cboGioiTinhActionPerformed(java.awt.event.ActionEvent evt) {                                           
        // TODO add your handling code here:
    }     
    
   

    // Variables declaration - do not modify                     
    private javax.swing.JButton btnLamMoi;
    private javax.swing.JButton btnSua;
    private javax.swing.JButton btnThem;
    private javax.swing.JButton btnTimKiem;
    private javax.swing.JButton btnXoa;
    private javax.swing.JComboBox cboChucVu;
    private javax.swing.JComboBox<String> cboGioiTinh;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private com.toedter.calendar.JDateChooser jdcNgayVaoLam;
    private javax.swing.JLabel lblCCCD;
    private javax.swing.JLabel lblChucVu;
    private javax.swing.JLabel lblDiaChi;
    private javax.swing.JLabel lblGioiTinh;
    private javax.swing.JLabel lblMaNV;
    private javax.swing.JLabel lblNgaySinh;
    private javax.swing.JLabel lblNgayVaoLam;
    private javax.swing.JLabel lblSDT;
    private javax.swing.JLabel lblTenNV;
    private javax.swing.JTable tblNhanVien;
    private javax.swing.JTextField txtCCCD;
    private javax.swing.JTextField txtDiaChi;
    private javax.swing.JTextField txtMaNV;
    private com.toedter.calendar.JDateChooser jdcNgaySinh;
    private javax.swing.JTextField txtSDT;
    private javax.swing.JTextField txtTenNV;
    private DefaultTableModel modeltblNV;
    private DefaultComboBoxModel modelCboChucVu;
    
    
    private DAONhanVien daoNhanVien = new DAONhanVien();
    private ArrayList<NhanVien> dsNV;
    // End of variables declaration                   
}
