package uiQuanLy;



public class GUIQuanLyVPP extends javax.swing.JPanel {

   /**
    * Creates new form NewJPanel
    */
   public GUIQuanLyVPP() {
       initComponents();
   }

   /**
    * This method is called from within the constructor to initialize the form.
    * WARNING: Do NOT modify this code. The content of this method is always
    * regenerated by the Form Editor.
    */
   @SuppressWarnings("unchecked")
   // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
   private void initComponents() {

       jPanel1 = new javax.swing.JPanel();
       lblLoaiVPP = new javax.swing.JLabel();
       lblDVT = new javax.swing.JLabel();
       lblQLVPP = new javax.swing.JLabel();
       lblMaVPP = new javax.swing.JLabel();
       txtMaVPP = new javax.swing.JTextField();
       lblTenSach = new javax.swing.JLabel();
       txtTenVPP = new javax.swing.JTextField();
       lblGiaNhap = new javax.swing.JLabel();
       lblNSX = new javax.swing.JLabel();
       lblSoLuong = new javax.swing.JLabel();
       txtSoLuong = new javax.swing.JTextField();
       btnThem = new javax.swing.JButton();
       btnXoa = new javax.swing.JButton();
       btnSua = new javax.swing.JButton();
       btnLamMoi = new javax.swing.JButton();
       jScrollPane1 = new javax.swing.JScrollPane();
       tblSach = new javax.swing.JTable();
       txtGiaNhap = new javax.swing.JTextField();
       lblGiaBan = new javax.swing.JLabel();
       txtGiaBan = new javax.swing.JTextField();
       btnTimKiemSach = new javax.swing.JButton();
       cbNSX = new javax.swing.JComboBox<>();
       cbDVT = new javax.swing.JComboBox<>();
       cbLoai = new javax.swing.JComboBox<>();

       jPanel1.setPreferredSize(new java.awt.Dimension(1536, 650));

       lblLoaiVPP.setText("Loại:");

       lblDVT.setText("Đơn vị tính:");

       lblQLVPP.setFont(new java.awt.Font("Arial", 1, 30)); // NOI18N
       lblQLVPP.setText("QUẢN LÝ VĂN PHÒNG PHẨM");

       lblMaVPP.setText("Mã văn phòng phẩm:");
       lblMaVPP.setToolTipText("");

       txtMaVPP.addActionListener(new java.awt.event.ActionListener() {
           public void actionPerformed(java.awt.event.ActionEvent evt) {
               txtMaVPPActionPerformed(evt);
           }
       });

       lblTenSach.setText("Tên văn phòng phẩm:");

       txtTenVPP.addActionListener(new java.awt.event.ActionListener() {
           public void actionPerformed(java.awt.event.ActionEvent evt) {
               txtTenVPPActionPerformed(evt);
           }
       });

       lblGiaNhap.setText("Giá nhập:");

       lblNSX.setText("Nhà SX:");

       lblSoLuong.setText("Số lượng:");

       txtSoLuong.addActionListener(new java.awt.event.ActionListener() {
           public void actionPerformed(java.awt.event.ActionEvent evt) {
               txtSoLuongActionPerformed(evt);
           }
       });

       btnThem.setText("Thêm");

       btnXoa.setText("Xóa");

       btnSua.setText("Sửa");
       btnSua.addActionListener(new java.awt.event.ActionListener() {
           public void actionPerformed(java.awt.event.ActionEvent evt) {
               btnSuaActionPerformed(evt);
           }
       });

       btnLamMoi.setText("Làm mới");

       tblSach.setModel(new javax.swing.table.DefaultTableModel(
           new Object [][] {
               {null, null, null, null, null, null, null, null, null},
               {null, null, null, null, null, null, null, null, null},
               {null, null, null, null, null, null, null, null, null},
               {null, null, null, null, null, null, null, null, null}
           },
           new String [] {
               "STT", "Mã Văn Phòng Phẩm", "Tên văn phòng phẩm", "Nhà sản xuất", "Loại ", "Đơn vị tính", "Giá nhập", "Giá bán", "Số lượng"
           }
       ) {
           Class[] types = new Class [] {
               java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class
           };

           public Class getColumnClass(int columnIndex) {
               return types [columnIndex];
           }
       });
       tblSach.addInputMethodListener(new java.awt.event.InputMethodListener() {
           public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
               tblSachCaretPositionChanged(evt);
           }
           public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
           }
       });
       jScrollPane1.setViewportView(tblSach);

       txtGiaNhap.addActionListener(new java.awt.event.ActionListener() {
           public void actionPerformed(java.awt.event.ActionEvent evt) {
               txtGiaNhapActionPerformed(evt);
           }
       });

       lblGiaBan.setText("Giá bán:");

       txtGiaBan.addActionListener(new java.awt.event.ActionListener() {
           public void actionPerformed(java.awt.event.ActionEvent evt) {
               txtGiaBanActionPerformed(evt);
           }
       });

       btnTimKiemSach.setText("Tìm kiếm");
       btnTimKiemSach.addActionListener(new java.awt.event.ActionListener() {
           public void actionPerformed(java.awt.event.ActionEvent evt) {
               btnTimKiemSachActionPerformed(evt);
           }
       });

       cbNSX.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

       cbDVT.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

       cbLoai.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

       javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
       jPanel1.setLayout(jPanel1Layout);
       jPanel1Layout.setHorizontalGroup(
           jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
           .addGroup(jPanel1Layout.createSequentialGroup()
               .addGap(338, 338, 338)
               .addComponent(btnThem, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
               .addGap(43, 43, 43)
               .addComponent(btnXoa, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
               .addGap(258, 258, 258)
               .addComponent(btnLamMoi, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
               .addGap(0, 0, Short.MAX_VALUE))
           .addGroup(jPanel1Layout.createSequentialGroup()
               .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                   .addGroup(jPanel1Layout.createSequentialGroup()
                       .addGap(72, 72, 72)
                       .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                           .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1369, javax.swing.GroupLayout.PREFERRED_SIZE)
                           .addGroup(jPanel1Layout.createSequentialGroup()
                               .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                   .addComponent(lblMaVPP)
                                   .addComponent(lblNSX))
                               .addGap(15, 15, 15)
                               .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                   .addComponent(txtMaVPP, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                                   .addComponent(cbNSX, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
                               .addGap(81, 81, 81)
                               .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                   .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                       .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                           .addComponent(lblTenSach)
                                           .addComponent(lblGiaNhap))
                                       .addGap(8, 8, 8)
                                       .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                           .addGroup(jPanel1Layout.createSequentialGroup()
                                               .addComponent(txtGiaNhap, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                               .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                               .addComponent(txtGiaBan, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                                           .addComponent(txtTenVPP, javax.swing.GroupLayout.PREFERRED_SIZE, 343, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                   .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                       .addComponent(lblGiaBan)
                                       .addComponent(btnSua, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)))
                               .addGap(38, 38, 38)
                               .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                   .addComponent(lblDVT)
                                   .addComponent(lblLoaiVPP))
                               .addGap(24, 24, 24)
                               .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                   .addComponent(cbLoai, 0, 128, Short.MAX_VALUE)
                                   .addComponent(cbDVT, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                               .addGap(37, 37, 37)
                               .addComponent(lblSoLuong)
                               .addGap(18, 18, 18)
                               .addComponent(txtSoLuong, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))))
                   .addGroup(jPanel1Layout.createSequentialGroup()
                       .addGap(667, 667, 667)
                       .addComponent(btnTimKiemSach, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)))
               .addContainerGap(95, Short.MAX_VALUE))
           .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
               .addGap(0, 0, Short.MAX_VALUE)
               .addComponent(lblQLVPP, javax.swing.GroupLayout.PREFERRED_SIZE, 454, javax.swing.GroupLayout.PREFERRED_SIZE)
               .addGap(528, 528, 528))
       );
       jPanel1Layout.setVerticalGroup(
           jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
           .addGroup(jPanel1Layout.createSequentialGroup()
               .addGap(22, 22, 22)
               .addComponent(lblQLVPP, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
               .addGap(18, 18, 18)
               .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                   .addComponent(lblMaVPP)
                   .addComponent(txtMaVPP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                   .addComponent(lblTenSach)
                   .addComponent(txtTenVPP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                   .addComponent(lblLoaiVPP)
                   .addComponent(cbLoai, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
               .addGap(22, 22, 22)
               .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                   .addComponent(lblNSX)
                   .addComponent(lblGiaNhap)
                   .addComponent(txtGiaNhap, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                   .addComponent(lblGiaBan)
                   .addComponent(txtGiaBan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                   .addComponent(lblDVT)
                   .addComponent(lblSoLuong)
                   .addComponent(txtSoLuong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                   .addComponent(cbNSX, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                   .addComponent(cbDVT, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
               .addGap(18, 18, 18)
               .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                   .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                       .addComponent(btnXoa, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                       .addComponent(btnSua, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                   .addComponent(btnLamMoi, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                   .addComponent(btnThem, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
               .addGap(22, 22, 22)
               .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 314, javax.swing.GroupLayout.PREFERRED_SIZE)
               .addGap(22, 22, 22)
               .addComponent(btnTimKiemSach, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
               .addContainerGap())
       );

       javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
       this.setLayout(layout);
       layout.setHorizontalGroup(
           layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
           .addGap(0, 1548, Short.MAX_VALUE)
           .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addGroup(layout.createSequentialGroup()
                   .addContainerGap()
                   .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                   .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
       );
       layout.setVerticalGroup(
           layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
           .addGap(0, 684, Short.MAX_VALUE)
           .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addGroup(layout.createSequentialGroup()
                   .addContainerGap()
                   .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 672, javax.swing.GroupLayout.PREFERRED_SIZE)
                   .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
       );
   }// </editor-fold>                        

   private void txtMaVPPActionPerformed(java.awt.event.ActionEvent evt) {                                         
       // TODO add your handling code here:
   }                                        

   private void txtTenVPPActionPerformed(java.awt.event.ActionEvent evt) {                                          
       // TODO add your handling code here:
   }                                         

   private void txtSoLuongActionPerformed(java.awt.event.ActionEvent evt) {                                           
       // TODO add your handling code here:
   }                                          

   private void btnSuaActionPerformed(java.awt.event.ActionEvent evt) {                                       
       // TODO add your handling code here:
   }                                      

   private void tblSachCaretPositionChanged(java.awt.event.InputMethodEvent evt) {                                             
       // TODO add your handling code here:
   }                                            

   private void txtGiaNhapActionPerformed(java.awt.event.ActionEvent evt) {                                           
       // TODO add your handling code here:
   }                                          

   private void txtGiaBanActionPerformed(java.awt.event.ActionEvent evt) {                                          
       // TODO add your handling code here:
   }                                         

   private void btnTimKiemSachActionPerformed(java.awt.event.ActionEvent evt) {                                               
       // TODO add your handling code here:
   }                                              


   // Variables declaration - do not modify                     
   private javax.swing.JButton btnLamMoi;
   private javax.swing.JButton btnSua;
   private javax.swing.JButton btnThem;
   private javax.swing.JButton btnTimKiemSach;
   private javax.swing.JButton btnXoa;
   private javax.swing.JComboBox<String> cbDVT;
   private javax.swing.JComboBox<String> cbLoai;
   private javax.swing.JComboBox<String> cbNSX;
   private javax.swing.JPanel jPanel1;
   private javax.swing.JScrollPane jScrollPane1;
   private javax.swing.JLabel lblDVT;
   private javax.swing.JLabel lblGiaBan;
   private javax.swing.JLabel lblGiaNhap;
   private javax.swing.JLabel lblLoaiVPP;
   private javax.swing.JLabel lblMaVPP;
   private javax.swing.JLabel lblNSX;
   private javax.swing.JLabel lblQLVPP;
   private javax.swing.JLabel lblSoLuong;
   private javax.swing.JLabel lblTenSach;
   private javax.swing.JTable tblSach;
   private javax.swing.JTextField txtGiaBan;
   private javax.swing.JTextField txtGiaNhap;
   private javax.swing.JTextField txtMaVPP;
   private javax.swing.JTextField txtSoLuong;
   private javax.swing.JTextField txtTenVPP;
   // End of variables declaration                   
   //hh
}