/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package uiTimKiem;

import javax.swing.DefaultComboBoxModel;
import javax.swing.JComboBox;

import entity.LoaiSanPham;

/**
 *
 * @author MSII
 */
public class FormTimKiemVPP extends javax.swing.JPanel {
	
    public JComboBox<LoaiSanPham> getcboLoai() {
		return cboLoai;
	}

	public void setcboLoai(JComboBox<LoaiSanPham> cboLoai) {
		this.cboLoai = cboLoai;
	}

	public javax.swing.JTextField getTxtTenNSX() {
		return txtTenNSX;
	}

	public void setTxtTenNSX(javax.swing.JTextField txtTenNSX) {
		this.txtTenNSX = txtTenNSX;
	}

	public javax.swing.JTextField getTxtTenVPP() {
		return txtTenVPP;
	}

	public void setTxtTenVPP(javax.swing.JTextField txtTenVPP) {
		this.txtTenVPP = txtTenVPP;
	}

	/**
     * Creates new form GUITimKiemNhanVien
     */
    public FormTimKiemVPP() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        lblLoaiVPP = new javax.swing.JLabel();
        lblTenNSX = new javax.swing.JLabel();
        txtTenVPP = new javax.swing.JTextField();
        lblTimKiemNV = new javax.swing.JLabel();
        lblTenVPP = new javax.swing.JLabel();
        txtTenNSX = new javax.swing.JTextField();
        cboLoai = new javax.swing.JComboBox<>();

      

        lblLoaiVPP.setText("Loại VPP:");

        lblTenNSX.setText("Tên NSX:");

        lblTimKiemNV.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblTimKiemNV.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTimKiemNV.setText("Tìm kiếm văn phòng phẩm");

        lblTenVPP.setText("Tên VPP:");

        modelcboLoai = new DefaultComboBoxModel<LoaiSanPham>();
        cboLoai.setModel(modelcboLoai);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(56, 56, 56)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblTenNSX)
                            .addComponent(lblLoaiVPP)
                            .addComponent(lblTenVPP))
                        .addGap(64, 64, 64)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(txtTenVPP, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 245, Short.MAX_VALUE)
                            .addComponent(txtTenNSX)
                            .addComponent(cboLoai, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(95, 95, 95)
                        .addComponent(lblTimKiemNV)))
                .addContainerGap(76, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(lblTimKiemNV)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTenVPP)
                    .addComponent(txtTenVPP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblLoaiVPP)
                    .addComponent(cboLoai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTenNSX)
                    .addComponent(txtTenNSX, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(55, Short.MAX_VALUE))
        );

        
    }// </editor-fold>                        

    /**
     * @param args the command line arguments
     */
   

    // Variables declaration - do not modify                     
   
    private javax.swing.JLabel lblLoaiVPP;
    private javax.swing.JLabel lblTenNSX;
    private javax.swing.JLabel lblTenVPP;
    private javax.swing.JLabel lblTimKiemNV;
    private javax.swing.JTextField txtTenNSX;
    private javax.swing.JTextField txtTenVPP;
    private javax.swing.JComboBox<LoaiSanPham> cboLoai;
    private DefaultComboBoxModel<LoaiSanPham> modelcboLoai;
    // End of variables declaration                   
}
