/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package uiTimKiem;

import javax.swing.DefaultComboBoxModel;
import javax.swing.JComboBox;

import entity.LoaiSanPham;

/**
 *
 * @author MSII
 */
public class FormTimKiemSach extends javax.swing.JPanel {
	
    public JComboBox<LoaiSanPham> getCboLoai() {
		return cboLoai;
	}

	public void setcboLoai(JComboBox<LoaiSanPham> cboLoai) {
		this.cboLoai = cboLoai;
	}

	public javax.swing.JTextField getTxtTenSach() {
		return txtTenSach;
	}

	public void setTxtTenSach(javax.swing.JTextField txtTenSach) {
		this.txtTenSach = txtTenSach;
	}

	public javax.swing.JTextField getTxtTenTacGia() {
		return txtTenTacGia;
	}

	public void setTxtTenTacGia(javax.swing.JTextField txtTenTacGia) {
		this.txtTenTacGia = txtTenTacGia;
	}

	/**
     * Creates new form GUITimKiemNhanVien
     */
    public FormTimKiemSach() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        lblLoaiSach = new javax.swing.JLabel();
        lblTenTacGia = new javax.swing.JLabel();
        txtTenSach = new javax.swing.JTextField();
        lblTimKiemNV = new javax.swing.JLabel();
        lblTenSach = new javax.swing.JLabel();
        txtTenTacGia = new javax.swing.JTextField();
        cboLoai = new javax.swing.JComboBox<>();

        

        lblLoaiSach.setText("Loại sách:");

        lblTenTacGia.setText("Tên tác giả:");

        lblTimKiemNV.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblTimKiemNV.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTimKiemNV.setText("Tìm kiếm sách");

        lblTenSach.setText("Tên sách:");

        modelcboLoai = new DefaultComboBoxModel<LoaiSanPham>();
        cboLoai.setModel(modelcboLoai);
       

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(203, Short.MAX_VALUE)
                .addComponent(lblTimKiemNV)
                .addGap(136, 136, 136))
            .addGroup(layout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblTenTacGia)
                    .addComponent(lblLoaiSach)
                    .addComponent(lblTenSach))
                .addGap(64, 64, 64)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(txtTenSach, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 245, Short.MAX_VALUE)
                    .addComponent(txtTenTacGia)
                    .addComponent(cboLoai, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(lblTimKiemNV)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTenSach)
                    .addComponent(txtTenSach, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblLoaiSach)
                    .addComponent(cboLoai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTenTacGia)
                    .addComponent(txtTenTacGia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(55, Short.MAX_VALUE))
        );

        
    }// </editor-fold>                        

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify                     
   
    private javax.swing.JLabel lblLoaiSach;
    private javax.swing.JLabel lblTenSach;
    private javax.swing.JLabel lblTenTacGia;
    private javax.swing.JLabel lblTimKiemNV;
    private javax.swing.JTextField txtTenSach;
    private javax.swing.JTextField txtTenTacGia;
    private javax.swing.JComboBox<LoaiSanPham> cboLoai;
    private DefaultComboBoxModel<LoaiSanPham> modelcboLoai;
    // End of variables declaration                   
}
